#################################################
# DO NOT CHANGE 
CONFIG_NAME: 'text-to-image'

DATASET_NAME: 'birds'
EMBEDDING_TYPE: 'cnn-rnn'
DATA_DIR: 'data/birds'

IMAGE_SIZE: 128
CUDA: True
WRONG_CAPTION: 9

CHECKPOINT_DIR: './checkpoints'
#################################################

GPU_ID: '0, 1'
WORKERS: 8

BATCH_SIZE: 256
CA: True
TREE:
    BASE_SIZE: 32
    BRANCH_NUM: 3


#################################################
# DO NOT CHANGE
TRAIN:
    FLAG: True
#################################################
    CNN_ENCODER: './evaluation/sim_models/bird/image_encoder.pth'
    RNN_ENCODER: './evaluation/sim_models/bird/text_encoder.pth'
    GENERATOR: 'birds_valid299/model.ckpt'

    COEFF:
        UNCOND_LOSS: 1.0
        KL: 2.0

    MAX_EPOCH: 400
    SNAPSHOT_INTERVAL: 50
    DISCRIMINATOR_LR: 0.0004
    GENERATOR_LR: 0.0004

#################################################
# DO NOT CHANGE 
TEST:
    B_EXAMPLE: False
    GENERATED_TEST_IMAGES: './evaluation/generated_images'
#################################################


RNN:
    TYPE: 'LSTM'
    
GAN:
    DF_DIM: 32
    GF_DIM: 32
    Z_DIM: 100
    CONDITION_DIM: 100
    R_NUM: 2
    EMBEDDING_DIM: 256
    
#################################################
# DO NET CHANGE 
TEXT:
    CAPTIONS_PER_IMAGE: 10
#################################################
    EMBEDDING_DIM: 256
    WORDS_NUM: 18